### ISSUE TITLE
It seems that `proxy.count` cannot be accessed

### ISSUE THREAD

**Issue by mu001999** [TOETOE55/dep-inj#3]
In the article [Exploring Design Patterns in Rust Inter-Component Interface Invocation](https://github.com/TOETOE55/dep-inj/blob/master/doc/Exploring%20Design%20Patterns%20in%20Rust%20Inter-Component%20Interface%20Invocation.md), I am confused by the following example:
```rust
fn is_even_impl(
    // Using trait object theoretically can speed up compilation because the code generation doesn't need to wait for generic instantiation.
    proxy: &mut EvenProxy<dyn Odd>,
    n: u64,
) -> bool {
    proxy.count += 1;

    (n == 0) || proxy
        .ctx // invoke is_odd through ctx
        .is_odd(n - 1)
}
```

Is this statement `proxy.count += 1` a mistake? Because we cannot get `dyn Odd: Ctx: AsMut<EvenState>` here, then we cannot use `proxy` as `&mut EvenState`, I guess.

**Comment by TOETOE55** [comment]
Oh, I make some mistakes. [Here](https://github.com/TOETOE55/dep-inj/blob/master/example/even-impl/src/lib.rs#L37) is the right implementation...

`EvenProxy<impl AsRef<EvenState> + AsMut<EvenState>>` would impl `DerefMut<Target = EvenState>`
